"""first commit

Revision ID: 1fb59554f76e
Revises: 
Create Date: 2022-12-19 22:13:08.881592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb59554f76e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=True),
    sa.Column('saved_to_readwise', sa.BOOLEAN(), nullable=True),
    sa.Column('save_time', sa.String(length=128), nullable=True),
    sa.Column('readwise_resp', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
