"""add content column

Revision ID: 76afaed937d9
Revises: 1fb59554f76e
Create Date: 2022-12-19 22:14:33.827078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76afaed937d9'
down_revision = '1fb59554f76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
