"""add publish_time

Revision ID: 9e74866c38ad
Revises: ce93e6f2d510
Create Date: 2022-12-19 23:57:08.547298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e74866c38ad'
down_revision = 'ce93e6f2d510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('publish_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'publish_time')
    # ### end Alembic commands ###
