"""add create_time, modify_time column

Revision ID: ce93e6f2d510
Revises: 76afaed937d9
Create Date: 2022-12-19 22:15:52.222123

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ce93e6f2d510'
down_revision = '76afaed937d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # alembic will auto recreate table with data migrated
    with op.batch_alter_table("article") as batch_op:
        batch_op.add_column(
            sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(
            sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'update_time')
    op.drop_column('article', 'create_time')
    # ### end Alembic commands ###
